{
 "title": "Sleep Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Average sleep time last 7 days ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  date AS \"time\",\r\n  CAST(total_sleep_duration /3600.0 AS DOUBLE PRECISION) as total_sleep_d\r\n\r\nFROM\r\n  sleep_sessions \r\nWHERE\r\ntotal_sleep_duration IS NOT NULL AND total_sleep_duration <> 0 AND \r\n  date >= current_date at time zone 'UTC' - interval '7 days'\r\n  \r\nGROUP BY\r\n  date\r\nORDER BY\r\n  date"
    }
   ]
  },
  {
   "title": "Average sleep efficiency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "target": "SELECT ... FROM ..." }
   ]
  },
  {
   "title": "Average sleep duration",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurationhms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "target": "SELECT ... FROM ..." }
   ]
  },
  {
   "title": "% of Nights above 7 hours",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (SUM(CASE WHEN total_sleep_duration > 7 * 60 * 60 THEN 1 ELSE 0 END) * 100.0 / COUNT(*)) AS percentage_of_nights_above_7_hours\r\nFROM\r\n  your_table_name\r\nWHERE\r\n  $__timeFilter(date)",
     "target": "SELECT ... FROM ..."
    }
   ]
  },
  {
   "title": "Sleep score",
   "type": "stat",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT score, date AS \"time\" FROM sleep_sessions LIMIT 50 ",
     "target": "SELECT score as \"Sleep Score\", date FROM sleep_sessions WHERE $__timeFilter(date)"
    }
   ]
  },
  {
   "title": "Oura sleep score (breakdown)",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "target": "SELECT rem_sleep, deep_sleep, efficiency, latency, restfulness, timing, total_sleep, date FROM sleep_sessions WHERE $__timeFilter(date)"
    }
   ]
  },
  {
   "title": "Sleep durations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT total_sleep_duration, date AS \"time\" FROM sleep_sessions \r\n\r\nWHERE\r\n  $__timeFilter(date)\r\nGROUP BY\r\n  date\r\nORDER BY\r\n  date\r\n",
     "target": "SELECT deep_sleep_duration, rem_sleep_duration, total_sleep_duration, time_in_bed, date FROM sleep_sessions WHERE $__timeFilter(date)"
    }
   ]
  }
 ]
}